https://www.youtube.com/watch?v=vyOgWhwUmec

## Bag of Words Approach

In [12]:
train_x  = ["i love the book", "this is a great book", "the fit is great", "i love the shoes"]

In [2]:
!pip install sklearn

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\npatel002\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.



Using legacy 'setup.py install' for sklearn, since package 'wheel' is not installed.
    Running setup.py install for sklearn: started
    Running setup.py install for sklearn: finished with status 'done'


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
vectorizer = CountVectorizer(binary=True)
vectors = vectorizer.fit_transform(train_x)

print(vectorizer.get_feature_names())
print(vectors.toarray())

['book', 'fit', 'great', 'is', 'love', 'shoes', 'the', 'this']
[[1 0 0 0 1 0 1 0]
 [1 0 1 1 0 0 0 1]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 1 1 0]]


C:\Users\npatel002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


Now we will build a simple model to categorize if the writing is for books or for clothing

In [18]:
class Category:
    BOOKS = "BOOKS"
    CLOTHING = "CLOTHING"

train_y = [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]

In [16]:
from sklearn import svm

In [7]:
clf_svm = svm.SVC(kernel='linear') #Good classification model for texts often times
clf_svm.fit(vectors, train_y)

SVC(kernel='linear')

In [8]:
test_x = vectorizer.transform(['i like the book'])
clf_svm.predict(test_x)

array(['BOOKS'], dtype='<U8')

In [9]:
test_x = vectorizer.transform(['shoes are alright'])
clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')

We can also have it see 2 words together (**bigram**) instead of just individual. For example, i love, love the, the book. Can prove to be important to capture sentiment, example, great not great.

In [10]:
vectorizer = CountVectorizer(binary=True, ngram_range=(1,2)) #sees 1 word and 2 words
vectors = vectorizer.fit_transform(train_x)

print(vectorizer.get_feature_names())
print(vectors.toarray())

['book', 'fit', 'fit is', 'great', 'great book', 'is', 'is great', 'love', 'love the', 'shoes', 'the', 'the book', 'the fit', 'the shoes', 'this', 'this is']
[[1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1]
 [0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0]]


C:\Users\npatel002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


**Limitation** : If the word is not in training occurances, it wont know how to handle it. This includes plural, capitals, different forms of the same word, etc.

## Word Vectors

Converts words into numeric value while capturng some of thet semantic meaning in the vector space that we are mapping the text to.

In [1]:
!pip install spacy

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


You should consider upgrading via the 'C:\Users\npatel002\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [2]:
!python -m spacy download en_core_web_md

#md - lg for large model. May take some time. sm for small.

  Attempting uninstall: en-core-web-md
    Found existing installation: en-core-web-md 3.2.0
    Uninstalling en-core-web-md-3.2.0:
      Successfully uninstalled en-core-web-md-3.2.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [3]:
import spacy

In [49]:
nlp = spacy.load("en_core_web_md")

In [13]:
docs = [nlp(text) for text in train_x]

In [14]:
docs

[i love the book, this is a great book, the fit is great, i love the shoes]

In [15]:
docs[0].vector

array([ 0.08563001,  0.313255  , -0.2392405 , -0.17215225,  0.1418515 ,
        0.1970548 ,  0.04868999, -0.12744625,  0.05947001,  2.1347    ,
       -0.61964   ,  0.01162549,  0.29980502, -0.125354  ,  0.017935  ,
       -0.1355105 , -0.27094752,  1.1129825 , -0.16986902, -0.0266875 ,
        0.14768225, -0.16372526,  0.121907  , -0.06876825, -0.061945  ,
        0.08704174, -0.2005705 , -0.24039775, -0.0675595 ,  0.0926495 ,
       -0.13526568,  0.24121101, -0.20299   ,  0.30007   ,  0.11574501,
        0.055062  ,  0.013516  , -0.0664179 , -0.3380587 , -0.17823698,
       -0.01039225,  0.03333575, -0.10241525, -0.093445  ,  0.09327275,
        0.20661727, -0.15074751,  0.14018372,  0.23520125, -0.05192125,
       -0.0999365 , -0.1212635 , -0.05895525, -0.005062  ,  0.06003174,
        0.01213001, -0.11257375, -0.24570274,  0.00678   , -0.1888345 ,
       -0.09276348, -0.25614128, -0.20717824,  0.0858725 , -0.02215025,
       -0.303222  , -0.00274375,  0.11888   ,  0.02695867,  0.20

In [17]:
wv_vectors = [x.vector for x in docs]

In [19]:
clf_svm_wv = svm.SVC(kernel='linear') #Good classification model for texts often times
clf_svm_wv.fit(wv_vectors, train_y)

SVC(kernel='linear')

In [22]:
test_x = ["i love the book"]
test_docs = [nlp(text) for text in test_x]
test_wv_vector = [x.vector for x in test_docs]
clf_svm_wv.predict(test_wv_vector)

array(['BOOKS'], dtype='<U8')

In [23]:
test_x = ["i love the story"]
test_docs = [nlp(text) for text in test_x]
test_wv_vector = [x.vector for x in test_docs]
clf_svm_wv.predict(test_wv_vector)

array(['BOOKS'], dtype='<U8')

In [24]:
test_x = ["i love the hat"]
test_docs = [nlp(text) for text in test_x]
test_wv_vector = [x.vector for x in test_docs]
clf_svm_wv.predict(test_wv_vector)

array(['CLOTHING'], dtype='<U8')

In [25]:
test_x = ["the shirt fits"]
test_docs = [nlp(text) for text in test_x]
test_wv_vector = [x.vector for x in test_docs]
clf_svm_wv.predict(test_wv_vector)

array(['CLOTHING'], dtype='<U8')

In [26]:
test_x = ["i love the color"]
test_docs = [nlp(text) for text in test_x]
test_wv_vector = [x.vector for x in test_docs]
clf_svm_wv.predict(test_wv_vector)

array(['CLOTHING'], dtype='<U8')

In [27]:
test_x = ["i love the color of the book"]
test_docs = [nlp(text) for text in test_x]
test_wv_vector = [x.vector for x in test_docs]
clf_svm_wv.predict(test_wv_vector)

array(['BOOKS'], dtype='<U8')

**Drawbacks**: more categories and more words - meanings of individual words might get lost in the embedding process and may not be that precise.

Does not handle words with multiple meaning. The word vector with both will be same.

## NLP Tools (*regex, stemming/lemmatization, stopwords removal*)

### Regex

examples:
- ab.*cd (starts with ab, any number of charcters in between, ends with cd)
- ab[^\s]*cd (starts with ab, not a white space, any number of characters, ends with cd)
- ^ab[^\s]*cd$ (^ - start of string, $ - end of string)

In [28]:
import re

In [30]:
regexp = re.compile(r"^ab[^\s]*cd$")

phrases = ['abcd', 'xxx', 'abxxxcd', 'ab cd']

matches = []
for phrase in phrases:
    if re.match(regexp,phrase):
        matches.append(phrase)

print(matches)

['abcd', 'abxxxcd']


In [31]:
regexp = re.compile(r"ab[^\s]*cd")

phrases = ['abcd', 'xxx', 'xx abxxxcd 123', 'ab cd'] 

#will not show the 3rd even though qualifies. Therefore, search.

matches = []
for phrase in phrases:
    if re.match(regexp,phrase):
        matches.append(phrase)

print(matches)

['abcd']


In [34]:
regexp = re.compile(r"ab[^\s]*cd")

phrases = ['abcd', 'xxx', 'xx abxxxcd 1234', 'ab cd']

matches = []
for phrase in phrases:
    if re.search(regexp,phrase):
        matches.append(phrase)

print(matches)

['abcd', 'xx abxxxcd 1234']


In [36]:
regexp = re.compile(r"read|story|book")
# | = or

phrases = ['i liked that story', 'i liked that book', 'this hat is nice', 'i like history']

matches = []
for phrase in phrases:
    if re.search(regexp,phrase):
        matches.append(phrase)

print(matches)

['i liked that story', 'i liked that book', 'i like history']


\b = word boundaries for strictly that word.

In [37]:
regexp = re.compile(r"\bread\b|\bstory\b|\bbook\b")
# | = or

phrases = ['i liked that story', 'i liked that book', 'this hat is nice', 'i like history']

matches = []
for phrase in phrases:
    if re.search(regexp,phrase):
        matches.append(phrase)

print(matches)

['i liked that story', 'i liked that book']


In [38]:
regexp = re.compile(r"\bread\b|\bstory\b|\bbook\b")
# | = or

phrases = ['i liked that story.', 'i liked that book', 'this hat is nice', 'i like history']

matches = []
for phrase in phrases:
    if re.search(regexp,phrase):
        matches.append(phrase)

print(matches)

['i liked that story.', 'i liked that book']


In [39]:
regexp = re.compile(r"\bread\b|\bstory\b|\bbook\b")
# | = or

phrases = ['i liked that story', 'i liked that book!', 'this hat is nice', 'i like history']

matches = []
for phrase in phrases:
    if re.search(regexp,phrase):
        matches.append(phrase)

print(matches)

['i liked that story', 'i liked that book!']


### Stemming/Lemmatization

- Technique to normalize text i.e books and book to book, reading to read Stories to stori while stemming and story with lemmatization (uses a dictationary to see if the word exist)

In [2]:
!pip install nltk

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\npatel002\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [3]:
import nltk

In [4]:
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

#### Stemming

In [5]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [6]:
stemmer = PorterStemmer()

phrase = "reading the books"
words = word_tokenize(phrase)

stemmed_words = [stemmer.stem(word) for word in words]

" ".join(stemmed_words)

'read the book'

In [7]:
stemmer = PorterStemmer()

phrase = "stories"
words = word_tokenize(phrase)

stemmed_words = [stemmer.stem(word) for word in words]

" ".join(stemmed_words)

'stori'

#### Lemmatizaion

In [8]:
from nltk.stem import WordNetLemmatizer

In [9]:
lemmatizer = WordNetLemmatizer()

In [10]:
phrase = "reading the stories"
words = word_tokenize(phrase)

lemmatized_words = [lemmatizer.lemmatize(word) for word in words]

" ".join(lemmatized_words)

'reading the story'

It assumes each is a noun. Therefore didnt change reading to read. But if we specify `pos='v'`, it will identify and change to read:

In [11]:
phrase = "reading the stories"
words = word_tokenize(phrase)

lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]

" ".join(lemmatized_words)

'read the stories'

maybe so lemmatize first with "n" and then stem?

### Stopwords Removal

In [12]:
from nltk.corpus import stopwords

In [13]:
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [14]:
len(stop_words)

179

In [15]:
phrase = "Here is an example sentence demonstrating the removal of stopwords"

words = word_tokenize(phrase)

stripped_phrase = [word for word in words if word not in stop_words]

" ".join(stripped_phrase)

'Here example sentence demonstrating removal stopwords'

## Various other Techniques (*spell correction, sentiment, pos (part of speech) tagging*) - **TextBlob Library**

Recommend to look into the documents. A lot of one line codes apart from what is demonstrated here.

In [16]:
!pip install textblob

You should consider upgrading via the 'C:\Users\npatel002\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [17]:
from textblob import TextBlob

In [19]:
phrase = "this is an exsample"

tb_phrase = TextBlob(phrase)

tb_phrase.correct()

TextBlob("this is an example")

In [22]:
nltk.download('averaged_perceptron_tagger') #given in the error message

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [25]:
!python -m textblob.download_corpora #not required

Finished.


[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\conll2000.zip.
[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\npatel002\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.

In [27]:
phrase = "i read the book"

tb_phrase = TextBlob(phrase)

tb_phrase.tags

[('i', 'NN'), ('read', 'VBD'), ('the', 'DT'), ('book', 'NN')]

In [28]:
tb_phrase.sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [32]:
def sentiment(phrase=""):
    tb_phrase = TextBlob(phrase)
    return tb_phrase.sentiment

In [33]:
sentiment("the book was great")

Sentiment(polarity=0.8, subjectivity=0.75)

In [36]:
sentiment("the book sucked it was so bad")

Sentiment(polarity=-0.6999999999999998, subjectivity=0.6666666666666666)

In [37]:
sentiment("the book sucked! It was so bad!")

Sentiment(polarity=-0.8749999999999998, subjectivity=0.6666666666666666)

In [38]:
print(sentiment("the book was horrible"))
print(sentiment("the book was horrible!"))

Sentiment(polarity=-1.0, subjectivity=1.0)
Sentiment(polarity=-1.0, subjectivity=1.0)


In [45]:
# phrase = "bonjour. Je suis une fille"

# tb_phrase = TextBlob(phrase)

# tb_phrase.detect_language()

# HTTP Error 400: Bad Request

In [44]:
phrase = "bonjour."

tb_phrase = TextBlob(phrase)

tb_phrase.detect_language()

'fr'

Recommends to use the Google transtale API since it has depreciated since version 0.16.0. New in version 0.5.0

## Recurrent Neural Networks

Addresses to the drawback of wor vectors where the model is s good as just the words in the training set.
- example: unlike word vectors, different embedding for the word check in the sentences chek out this book and write me a check.

Feed in one token at a time

**Drawbacks**

Longer dependencies dont always perform well. 
- for example: " i need to go to the bank today so that i can make a deposit, I hope it's not closed." By the time it comes to closed, it might not correctly interprete that "closed" is used for the bank, because it is so far out in the sentence.

Sequencial nature of RNN (feeding one token at a time) make it tough to paralllelize and  effectively use modern GPUs.

## Attention Networks

Positional encodingnetwork learns to ask questions about how the tokens are related to each other

## Transformer Architecture

- BERT (bi-directional transformer architecture, captures a lot about language. Even more than the OpenAI GPT.), 
- OpenAI GPT (can lso predict what the next word would be based on the training), 
- ELMo (not really a transformer architecture | uses RNNs)

### BERT Model

https://explosion.ai/blog/spacy-transformers

#### Installations

In [6]:
!pip install -U spacy

In [4]:
!pip install spacy-transformers
# !python -m spacy download en_trf_bertbaseuncased_lg

  Using cached spacy-3.2.0-cp39-cp39-win_amd64.whl (11.7 MB)
  Attempting uninstall: spacy
    Found existing installation: spacy 3.0.0
    Uninstalling spacy-3.0.0:


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\npatel002\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\~pacy\\attrs.cp39-win_amd64.pyd'
Check the permissions.



      Successfully uninstalled spacy-3.0.0


In [52]:
!python -m pip install --upgrade pip

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\npatel002\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [75]:
!python -m spacy download en_core_web_trf

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')


In [2]:
# nlp = spacy.load('en_core_web_trf')

In [61]:
!python -m spacy download en_trf_bertbaseuncased_md


✘ No compatible package found for 'en_trf_bertbaseuncased_md' (spaCy v3.2.0)



In [65]:
!python -m spacy download en_trf_bertbaseuncased_sm


✘ No compatible package found for 'en_trf_bertbaseuncased_sm' (spaCy v3.2.0)



In [13]:
!python -m spacy download en_trf_bertbaseuncased_lg


✘ No compatible package found for 'en_trf_bertbaseuncased_lg' (spaCy v3.0.0rc5)



In [70]:
!pip install -U pip setuptools wheel

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [72]:
!pip install -U spacy

In [9]:
# !pip install spacy-nightly

In [10]:
# nlp = spacy.load("en_trf_bertbaseuncased_sm")

In [1]:
!pip list

Package            Version
------------------ ----------
backcall           0.2.0
blis               0.7.5
catalogue          2.0.6
certifi            2021.10.8
charset-normalizer 2.0.7
click              7.1.2
colorama           0.4.4
cymem              2.0.6
debugpy            1.5.1
decorator          5.1.0
en-core-web-md     3.0.0
en-core-web-trf    3.2.0
entrypoints        0.3
filelock           3.4.0
huggingface-hub    0.1.2
idna               3.3
ipykernel          6.5.0
ipython            7.29.0
jedi               0.18.0
Jinja2             3.0.3
joblib             1.1.0
jupyter-client     7.0.6
jupyter-core       4.9.1
langcodes          3.3.0
MarkupSafe         2.0.1
matplotlib-inline  0.1.3
murmurhash         1.0.6
nest-asyncio       1.5.1
nltk               3.6.5
numpy              1.21.4
packaging          21.2
parso              0.8.2
pathy              0.6.1
pickleshare        0.7.5
pip                21.3.1
preshed            3.0.6
prompt-toolkit     3.0.22
pydantic      

In [68]:
!python -m pip install --upgrade spacy

In [1]:
!pip install spacy==3.0

  Attempting uninstall: spacy
    Found existing installation: spacy 3.2.0
    Uninstalling spacy-3.2.0:
      Successfully uninstalled spacy-3.2.0


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy-transformers 1.1.2 requires spacy<4.0.0,>=3.1.3, but you have spacy 3.0.0 which is incompatible.
en-core-web-trf 3.2.0 requires spacy<3.3.0,>=3.2.0, but you have spacy 3.0.0 which is incompatible.
en-core-web-md 3.2.0 requires spacy<3.3.0,>=3.2.0, but you have spacy 3.0.0 which is incompatible.


In [8]:
!pip install spacy-nightly

  Using cached spacy_nightly-3.0.0rc5-cp39-cp39-win_amd64.whl (11.4 MB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [12]:
!pip install -U spacy
!python -m spacy

Usage: python -m spacy [OPTIONS] COMMAND [ARGS]...

  spaCy Command-line Interface

  DOCS: https://nightly.spacy.io/api/cli

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.

  --help                          Show this message and exit.

Commands:
  convert   Convert files into json or DocBin format for training.
  debug     Suite of helpful commands for debugging and profiling.
  download  Download compatible trained pipeline from the default download...
  evaluate  Evaluate a trained pipeline.
  info      Print info about spaCy installation.
  init      Commands for initializing configs and pipeline packages.
  package   Generate an installable Python package for a pipeline.
  pretrain  Pre-t

In [14]:
!pip uninstall spacy-nightly

#### Model

Same as word vector codes, instead of web_md, we use the bert spacy.load as nlp engine.

**Drawback**: Cant build off of this model.

**Solution**: huggingface/transformers github repo - has the entire model written in pytorch. So you can build off of that model or finetune it from the huggingface library. It also has various other models apart from bert.

## Excercise